### ISSUE TITLE
 No matching version found for @solid-aria/types@* inside the workspace

### ISSUE THREAD

**Issue by thetarnav** [solidjs-community/solid-aria#29]
![image](https://user-images.githubusercontent.com/24491503/174058144-fdc3844a-a767-480d-affc-e5477c34e9b6.png)

Was trying to install `@solid-aria/interactions`.

Are you sure you want to have `^workspace` instead of `^0.1.0` for the dependency version?
Changesets will update the versions automatically anyway.

**Comment by fabien-ml** [comment]
Looks like there is also issues when running `npm i`. Normallly pnpm should replace all "workspace: ^" by the actual version in the workspace, I don't why it failed. 
Do you want to publish a `0.1.1` which replace all `workspace: ^` by `^0.1.1` ?

**Comment by thetarnav** [comment]
Sure, I can do it today.
Just to make sure I get the publishing process:
- commit updates on a new branch
- run `changeset` to make a patch update with some "Replaced `workspace: ^` by `^0.1.1` dependency versions."
- make a PR to main
That's it?

**Comment by fabien-ml** [comment]
You should run `changeset` on your new branch, you can do it in the same commit with the changes.

The changeset bot will automatically detect the file and show you which packages will be updated
